### PR TITLE
2018 and 2019 Bagwell awards

### PR DESCRIPTION
**Pull request by SethTisue**
replaces #1068 and #1069, includes @darjutak's commits

### CODE REVIEW

**Comment by darjutak** [comment]
> Kelley approved her "about the winner" section

so we are only waiting on @jsuereth to upload the videos and we are good to go?

**Comment by SethTisue** [comment]
> so we are only waiting on @jsuereth to upload the videos 

correct

**Comment by SethTisue** [comment]
@jsuereth ping

(and if we don't hear back from Josh by Wednesday or so, I suggest we go ahead and publish anyway)

**Comment by SethTisue** [comment]
tribute video links are in. anyone know who the guy in the Kelley video who doesn't introduce himself is, around 1:45? I put an "and others", but I'll replace it with a name if someone can identify him.

**Pull request merged**
