### PR TITLE
create nov slip meeting notes

### PR DESCRIPTION
**Pull request by hamishdickson**
I found parts of the recording hard to hear this month - please just say if I've missed anything you feel is important

### CODE REVIEW

**Comment by sjrd** [comment]
You should not commit `.jekyll-metadata`.

**Comment by hamishdickson** [comment]
@sjrd oops!

**Comment by SethTisue** [comment]
> I found parts of the recording hard to hear this month

is there anyone in particular who should get a reminder to check their config, use a headset, etc?

**Comment by SethTisue** [comment]
thank you Hamish, we really appreciate your help with this.

I made some light edits in 344f42bfc14a1b413615c988f6c80105d06c3094

**Comment by hamishdickson** [comment]
@SethTisue my pleasure - happy to help if it's useful and it frees people up to do other things

>> I found parts of the recording hard to hear this month

> is there anyone in particular who should get a reminder to check their config, use a headset, etc?

Oh not to the point where you can do anything about it - it was really just connection related, for example Sébastien's connection went a bit funny at one stage, as did yours. Sadly tech isn't perfect :disappointed:

**Pull request merged**
