### PR TITLE
2015-03-27-SpringPeople.md

### PR DESCRIPTION
**Pull request by rakeshsingh9901**
If you already have programming experience with Scala and want to understand its advanced features, this two-day course is for you. It is designed to help developers fully understand topics such as advanced object-functional programming, the power of Scala's type system, implicits, etc. The course also covers how to leverage these features to create well-designed libraries or DSL’s utilizing proven best practices

### CODE REVIEW

**Comment by sjrd** [comment]
The file name should match the start date.

**Comment by rakeshsingh9901** [comment]
Thanks for helping.
Done

**Comment by heathermiller** [comment]
This is also a course, not an event. So please move this over to the training feed instead.

**Comment by heathermiller** [comment]
(The training feed is in directory `training` rather than `events`)

**Comment by dickwall** [comment]
One is still in events, the other has expired - closing PR.

**Pull request closed without merging**
