### PR TITLE
Adding Discourse to community page, bringing CoC to parity with contributors.scala-lang

### PR DESCRIPTION
**Pull request by heathermiller**
review by @SethTisue

### CODE REVIEW

**Comment by SethTisue** [comment]
LGTM! (I would be fine with removing the links to the retired mailing lists, but if you think it's better to wait, that's fine too.)

**Comment by heathermiller** [comment]
Thanks @SethTisue! 

RE: the retired mailing lists, I think it's worth keeping links to them around as an archive at the very least. There's plenty of useful information still in them. Regardless, we'll keep the links around a bit :)

**Comment by SethTisue** [comment]
I reviewed this too quickly -- it's messed up, with broken links, scala-user link removed even though the users site isn't launched yet, etc. I'm working on a followup PR.

**Comment by SethTisue** [comment]
followup is #589

**Pull request merged**
