### PR TITLE
Blog post announcing Community Representative

### PR DESCRIPTION
**Pull request by propensive**

### CODE REVIEW

**Comment by sjrd** [comment]
Title suggestion:

> The Scala Center Appoints Bill Venners as Community Representative to the Advisory Board

i.e., mention Bill's name directly in the title.

**Comment by heathermiller** [comment]
Agree with @sjrd :)

**Comment by propensive** [comment]
I left his name off not to spoil the surprise later on... but sure. The only problem is that the title will now flow onto two lines. Is that ok?

**Comment by heathermiller** [comment]
Sure

**Comment by heathermiller** [comment]
LGTM thanks :)

**Pull request merged**
