### PR TITLE
Add blog for the results of August SIP meeting

### PR DESCRIPTION
**Pull request by jvican**

### CODE REVIEW

**Comment by jvican** [comment]
This is to be merged tomorrow around 15:00PM (European Central Time, Zurich).

**Comment by SethTisue** [comment]
the links all start with `https://www.google.com/url?q=`, that looks unintentional?

**Comment by jvican** [comment]
Nope, thanks for the catch!

**Comment by jvican** [comment]
Actually, I have no merge rights here. Please, can someone merge on behalf of me?
  
/cc @heathermiller

**Comment by xeno-by** [comment]
Merged at exactly 15:00PM (European Central Time, Zurich).

**Comment by jvican** [comment]
Thanks Eugene, you're awesome.

**Pull request merged**
