### PR TITLE
Bagwell Award 2016 (don't merge til Oct 26)

### LINKED ISSUE #473: Erik Osheim receiving Phil Bagwell Award should be blog-posted
as was done for Bill V last year at http://www.scala-lang.org/news/2015/06/25/bagwell-award-2015.html — that post could be used as a template

@propensive I imagine you're swamped right now, but let's not let this fall through the cracks, either

### PR DESCRIPTION
**Pull request by SethTisue**
review by... @heathermiller? @propensive? @odersky? (@non?)

fixes #473

### CODE REVIEW

**Comment by heathermiller** [comment]
Thank you so much for picking this up Seth! Could we bump this to a Wednesday release? Only because we bumped Scalafix from today to tomorrow.

**Comment by heathermiller** [comment]
LGTM other than the date

**Comment by SethTisue** [comment]
> Could we bump this to a Wednesday release

done

**Comment by heathermiller** [comment]
Awesome, thanks!

**Comment by heathermiller** [comment]
Announced :)

**Pull request merged**
