### PR TITLE
Launching GSOC 2018!

### PR DESCRIPTION
**Pull request by MasseGuillaume**

### CODE REVIEW

**Comment by julienrf** [comment]
That looks good except that we should probably add a couple of project ideas. When do you plan to launch this page? In my understanding we should wait for the Scala organization to have been officially accepted (February 12).

**Comment by MasseGuillaume** [comment]
@julienrf I want to create the skeleton, we will add project ideas this week.

**Comment by MasseGuillaume** [comment]
ping @axel22 @cvogt @fommil @chipsenkbeil @dragos @wpopielarski @mlangc @sschaef @mutcianm

Hello, This year I'm the organization administrator for the GSoC. We are looking for mentors and project ideas. The Scala organization is applying but the project idea list is crucial to being selected. Your help would be greatly appreciated.

**Comment by fommil** [comment]
Sorry I can't do it this year, too many responsiblities at home. Good luck!

**Comment by fommil** [comment]
Btw please only add project ideas if you are willing to mentor them. Remove if you feel you cannot. The students are expecting to submit tenders to what they feel are invitations, we never get open proposals and it would be devastating if somebody spent a long time putting a proposal together but we have no mentor, so we have to reject them. I had several discussions with students along those lines last year.

Also, last year I did quite a bit of coordinating to ensure that when many students applied to one bid, they also put in a second proposal as a backup. My feeling was that most students wanted a GSOC, any GSOC, and the project itself didn't matter. I hope somebody takes on this role in a more formal way this year. Best of luck!

**Comment by MasseGuillaume** [comment]
@fommil thanks for your advice. The most important task I have right now is to find people that can fit in the role of mentor. They are what makes GSOC a great experience.

**Comment by fommil** [comment]
@masseguillaume one last thing, we've always struggled to get students to apply. In your role as coordinator if you spammed university lecturers that may help increase the input. I pinned a few uk university lecturers last year but it didn't help...

**Comment by MasseGuillaume** [comment]
@fommil this is a good idea, I'm taking notes. I will ask Martin O. if he has a list of universities using Scala as a teaching language.

**Comment by fommil** [comment]
You don't need that... any student who is keen on learning it is fine. They have several months to pick up Scala at the beginning and that's what students are good at ;-)

Indeed, it may well be that some Scala tools are best written in rust or haskell for performance... or purescript / python / lisp for integrations.

**Pull request merged**
