### PR TITLE
add resources to main index and add license to other download files

### PR DESCRIPTION
**Pull request by jarrodwb**
Possible fix for #448.

### CODE REVIEW

**Comment by SethTisue** [comment]
this would need a corresponding change in https://github.com/scala/make-release-notes, since that's how PRs such as #494 are created

not sure if you feel like going that route. perhaps there's some easier to way address #448?

**Comment by jarrodwb** [comment]
Is `scala-lang/download/index.md` auto-generated by `make-release-notes` or is it updated by hand? I don't see where the header of `index.md` is touched by `make-release-notes`.

I tried running:

```
MakeReleaseNotes.genPR("2.11.7", "2.11.8", "2016/03/08", "/home/jarrodwb/scala-lang/")
```

but I got an error

```
## fetching size of http://downloads.lightbend.com/scala/2.11.8/scala-2.11.8.tgz
## fetching size of http://downloads.lightbend.com/scala/2.11.8/scala-2.11.8.msi
## fetching size of http://downloads.lightbend.com/scala/2.11.8/scala-2.11.8.zip
## fetching size of http://downloads.lightbend.com/scala/2.11.8/scala-2.11.8.deb
## fetching size of http://downloads.lightbend.com/scala/2.11.8/scala-2.11.8.rpm
## fetching size of http://downloads.lightbend.com/scala/2.11.8/scala-docs-2.11.8.txz
## fetching size of http://downloads.lightbend.com/scala/2.11.8/scala-docs-2.11.8.zip
## fetching size of https://github.com/scala/scala/archive/v2.11.8.tar.gz
## warning: could not fetch https://github.com/scala/scala/archive/v2.11.8.tar.gz
cp 2016-03-08-2.11.8.md ../scala-lang/download/_posts/
# to prepare your scala-lang PR
fatal: ambiguous argument 'v2.11.7..v2.11.8': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
java.lang.RuntimeException: Nonzero exit code: 128
  at scala.sys.process.BasicIO$Streamed$.scala$sys$process$BasicIO$Streamed$$next$1(BasicIO.scala:49)
  at scala.sys.process.BasicIO$Streamed$$anonfun$apply$3.apply(BasicIO.scala:52)
  at scala.sys.process.BasicIO$Streamed$$anonfun$apply$3.apply(BasicIO.scala:52)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream(ProcessBuilderImpl.scala:144)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream(ProcessBuilderImpl.scala:107)
  at GitHelper$.processGitCommits(GitInfo.scala:12)
  at GitInfo.<init>(GitInfo.scala:42)
  at MakeReleaseNotes$.makeReleaseNotes(MakeReleaseNotes.scala:78)
  at MakeReleaseNotes$.apply(MakeReleaseNotes.scala:39)
  at MakeReleaseNotes$.genPR(MakeReleaseNotes.scala:11)
  ... 42 elided
,,,

From what I have gathered so far I think this PR should work. If I could do a dry-run of the next release then I would know for sure. The worst that would happen is that the `index.md` file would be overwritten in a new release and the bug would come back. The best that could happen is that the bug is fixed for good.

Any ideas?

**Comment by adriaanm** [comment]
> fatal: ambiguous argument 'v2.11.7..v2.11.8': unknown revision or path not in the working tree.

Looks like `/home/jarrodwb/scala-lang/` should be changed to where you have your https://github.com/scala/scala.git clone.

**Comment by SethTisue** [comment]
in `src/main/scala/MakeReleaseNotes.scala` we see:

```scala
println(s"# don't forget to\n${scala.util.Properties.envOrElse("EDITOR", "mate")} ../scala-lang/download/index.md ../scala-lang/documentation/api.md ../scala-lang/_config.yml")
```

so I guess index.md is hand-updated.

I hit "merge" on this assuming it still fixed #448, but I see that it doesn't, actually. if I hit "merge" before you were ready, sorry about that.

**Comment by jarrodwb** [comment]
Is this still an issue? I don't see any problems on the production site.

Granted it has been about a week since I looked at this. I took a trip to Hamburg.

**Comment by SethTisue** [comment]
I'm not totally sure we got all the loose ends here, since I keep forgetting the details since I've only been looking at this once or twice a week. But I _think_ Adriaan's manual fix took care of it, and then next time around, the manually updated file will be the basis for getting it right again in the next manual update. (It would be better if that were automated. I opened an issue on that: https://github.com/scala/make-release-notes/issues/236.)

**Comment by jarrodwb** [comment]
Sounds great. I was dealing with the same problem.

On a side note, I find it really interesting to work on something with so many different people. It is liberating to not have to know everything and to trust others.

Thanks

**Pull request merged**
