### PR TITLE
for local use, recommend Bundler and provide config

### PR DESCRIPTION
**Pull request by SethTisue**
so that people can test the site locally without having to
install stuff systemwide on their local machines

originally contributed by @soc as part of a larger PR (https://github.com/scala/scala-lang/pull/359), so I've
retained him as author on the commit.  the only significant thing I
(@SethTisue) did differently was specify Jekyll 2, not 3, in
Gemfile.lock, since Jekyll 2 is what we're using in production

### CODE REVIEW

**Comment by SethTisue** [comment]
review by @heathermiller and @fsalvi 

note that I have no idea how closely the components and versions in the Gemfile.lock match what is actually used in production.

however, I don't think that actually matters as far as merging this, because:

* unless I have failed to understand something, the changes here will not affect the production, only contributors trying to test locally
* the old instructions in the README gave no guidance about versions whatsoever, so it was a crapshoot and you were overwhelmingly likely to end up with something that didn't resemble the production setup at all, so although this PR may not makes thing perfect, I think it makes them a good deal better and does not make them worse

**Comment by SethTisue** [comment]
@heathermiller is this OK to merge...?

**Comment by fsalvi** [comment]
Well, I just tried it using the production server configuration, and it's not ok: /resources/js/vendor is missing because of the exclude line in _config.yml
I tried to remove this exclude line and it looks fine for the rest.

**Comment by SethTisue** [comment]
@fsalvi thanks for taking the time to test this. what version of Jekyll are we running in production?

it looks to me from https://github.com/jekyll/jekyll/issues/1915 that it should work in current Jekyll to use an initial slash to anchor the excluded path to the root. but to be sure this will work, I need to know what version of Jekyll is expected.

**Comment by heathermiller** [comment]
Not sure if this is running on chara, but:

    hmiller@chara:~$ jekyll --version
    /home/hmiller/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be deprecated in the future, use String#encode instead.
    Jekyll 0.11.2

So, it's old.

I've been told that Fabien plans on updating Ruby etc on that machine in the coming months, which should eventually enable us to upgrade to Jekyll 3.

**Comment by SethTisue** [comment]
wow, that is old!

OK, I'm going to close this for now while I think about whether to put together a Gemfile.lock with that version, or just wait for the upgrade, or what.

I would be eager to help with the upgrade (within the limits of my not very extensive experience with this stuff).

**Comment by fsalvi** [comment]
Well, before reinstalling the server (which I plan to do in April), we could upgrade to jekyll 1.5.1 if this is useful...

**Comment by heathermiller** [comment]
It probably is useful!

**Comment by SethTisue** [comment]
yes, moving to 1.5.1 would be a huge improvement

**Comment by SethTisue** [comment]
to respond to Heather's questions on Gitter:

>why can't you preview locally?
>Is it really such a big deal to install Jekyll?

yes, this is a blocker for me. @soc obviously considers it important as well.

scala-lang isn't the only Ruby app on my machine, and I'm not willing to make global visible changes to my Ruby setup in order to preview changes to one website. partly because I consider it undesirable; partly because I lack the knowledge and competence to troubleshoot any resulting conflicts; and partly because I think it's undesirable to impose this requirement on other contributors as well.

that's why I consider it essential for us to provide a proper Gemfile and Gemfile.lock. we already do this right over in the docs.scala-lang repo; we ought to do it right in this repo, too.

I'm not just griping — I want to fix it myself. I've been just moving slowly on it.

@fsalvi can you tell me exactly what version of Jekyll chara is running? is it 0.11.2? so far I only know what version Heather has installed on her local machine. if I'm going to go through the process of producing a Gemfile/Gemfile.lock combo for an old version of Jekyll (perhaps this will actually be quite easy? I don't know yet, I'm learning this stuff as I go), I would prefer to know beforehand exactly what Jekyll version I'm targeting.

**Comment by SethTisue** [comment]
P.S. perhaps this is all based on some misconception of mine. it's hard for me to be sure since I'm not expert on this stuff. over at #197, you said "I use Jekyll versions 1-3 across computers to build locally without issue". as far as I know, the only way that's possible is using Gemfile/Gemfile.lock, which we don't yet have in this repo?

**Comment by fsalvi** [comment]
Yes, it is:  jekyll -v
Jekyll 0.11.2

It has remained the same version since the development of the web site in July 2013.
But, I guess I could easily upgrade it to 1.5.1 as I did it for another website recently. I will do some tests to ensure this doesn't break anything and will upgrade it if it's ok soon (beginning of next week I guess).

**Comment by SethTisue** [comment]
awesome! I'm perfectly happy to postpone the Gemfile stuff a little while and wait for that upgrade.

**Comment by adriaanm** [comment]
The main reason I'd like to upgrade is that the current markdown parser is very broken. I've spent hours already trying to make stuff parse that previews just fine locally and on github. Almost 20% of my commits in this repo are to fix maruku issues:

57112dfcd6 (HEAD -> 2016-update) last formatting tweak
d86a1c0d39 ok, how about a table then?
3ec0be5e5a ffs maruku, just render the bullets already
cad933af34 fix formatting error, slight reword
6566cf9cfd Add break to 2.10.6 announcement
1d31e06601 (adriaanm/master) Remove comment to unbreak homepage?
46fd13e317 Unbreak front page by limiting blurb?
d81582396e (adriaanm/2.11.5, 2.11.5) Appease maruku 0.6.1: no leading @s
3e855d1fe8 Remove trailing comma, appease Maruku?
f1eacc5347 fix formatting in 2.12 roadmap
c24bf7b181 please, maruku, tell me this works
fab57d03b6 fix markdown formatting, tweak eclipse bit

**Comment by soc** [comment]
I switched to redcarpet recently, because that's the one used ("required") by the Scala spec, and have been pretty happy so far. As far as I know, maruku is considered to be obsolete by its authors, and Jekyll switched to another parser in 2.0 ... (kramdown?).

Kramdown should work fine, too, I just picked redcarpet because of all the special options being used for the spec, and it working fine with content from both scala-lang, docs.scala-lang and the spec.

**Comment by heathermiller** [comment]
@fsalvi the ball is your court. Redcarpet or kramdown or whatever one elects to use is another dependency that must be added to the build machine.

**Comment by fsalvi** [comment]
Well, I just did a test using kramdown to build the website and it looks ok. It's even much fast, 10s for kramdown instead of 59s for maruku ! I will switch to it next week on the production server in the same time I upgrade jekyll.

**Comment by heathermiller** [comment]
Awesome, thanks Fabien :)

**Comment by adriaanm** [comment]
Thanks, @fsalvi!

**Comment by fsalvi** [comment]
Ok, I just did the modifcations and built the website. It looks good, but let me know if you see anything wrong. Thanks.

**Comment by SethTisue** [comment]
thanks so much @fsalvi. I haven't noticed any problems on the site in the last few days.

**Comment by SethTisue** [comment]
successor PR at #373

**Pull request closed without merging**
