### PR TITLE
Add Some Upcoming Events

### PR DESCRIPTION
**Pull request by khajavi**

### CODE REVIEW

**Review by Philippus — CHANGES_REQUESTED** [review]
Adding events works a little differently. Check this previous pr on how to add an event:
https://github.com/scala/scala-lang/pull/1460

**Comment by khajavi** [comment]
@Philippus Thank you for your quick response. I'll fix that shortly.

**Comment by Philippus** [comment]
I propose to drop the meetup/hackathon ones. We usually don't add those, only events with its own website.

**Comment by khajavi** [comment]
@Philippus 
It is ready for your review.

**Comment by Philippus** [comment]
Thanks!

**Pull request merged**
