### PR TITLE
2.11.7 release notes

### PR DESCRIPTION
**Pull request by adriaanm**
tweak of #303

### CODE REVIEW

**Comment by adriaanm** [comment]
Ready now for merge to do soft launch, as far as I'm concerned. /cc @SethTisue

**Comment by heathermiller** [comment]
Hi guys, I just noticed this now, but the front page of scala-lang is broken. I'm assuming it's from some rendering error in the release notes. Haven't had a chance to look at it, noticed it while getting ready for bed. If someone gets a second, would you mind debugging? Otherwise I can fix in the am.

**Comment by adriaanm** [comment]
I'll take a look. Probably need to move up the marker for the summary.

**Comment by adriaanm** [comment]
Fixed by #307

**Comment by heathermiller** [comment]
Awesome, thanks a lot Adriaan!

**Pull request merged**
