### PR TITLE
Blog post: community and communication

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

**Comment by SethTisue** [comment]
iiuc, this won't appear on the site right away due to some known problem in the deploy pipeline. tomorrow?

**Comment by odersky** [comment]
OK, tomorrow.

**Comment by odersky** [comment]
On second thought, is there a way to get this in faster? I believe it would be good to get it out sooner rather than later.

**Comment by SethTisue** [comment]
you'd have to ask @darjutak and/or @fsalvi

**Comment by darjutak** [comment]
I'd like to be able to help, but it's @fsalvi that can do something, and he's not around - maybe someone else from the Scala Center?

**Comment by julienrf** [comment]
How did we manage to get the changes of previous PRs (eg #1036) published?

**Comment by fsalvi** [comment]
It's now online.

**Comment by fsalvi** [comment]
The deploy pipeline is now fixed, both for scala-lang.org and scala.epfl.ch websites.

**Pull request merged**
