### PR TITLE
2016 Scala Release Schedule update

### PR DESCRIPTION
**Pull request by adriaanm**
Review by @heathermiller

### CODE REVIEW

**Comment by adriaanm** [comment]
Or can @sjrd sign off? We'd like to share this update soon.

**Comment by sjrd** [comment]
LGTM

**Comment by lrytz** [comment]
LGTM too

**Comment by heathermiller** [comment]
LGTM! apologies, missed the notification

**Comment by heathermiller** [comment]
Merge as you wish!

**Comment by adriaanm** [comment]
Thanks!

**Comment by SethTisue** [comment]
tweeted: https://twitter.com/scala_lang/status/674754558996819968

**Pull request merged**
