### PR TITLE
Online Intermediate Scala Public Enrollment 

### PR DESCRIPTION
**Pull request by mslinn**
Our second public enrollment course!

### CODE REVIEW

**Comment by SethTisue** [comment]
I tried this locally with `bundle exec jekyll serve` and when I click on the new event I get a 404 on http://0.0.0.0:4000/undefined

**Comment by mslinn** [comment]
Sounds like a regression. Seems similar to issues #478 and #484

**Comment by SethTisue** [comment]
hmm, for the October course it's broken locally but works on the real site. I don't know what to make of that. I guess I'll just merge this, and let's hope it works on the real site

**Comment by SethTisue** [comment]
yeah, seems OK

**Comment by SethTisue** [comment]
oh, except you forgot the `category: event` at the top. I supplied it in d727431236b997800e2d02bf1c5316e72bb5558c

**Comment by mslinn** [comment]
No, did not forget. For each of the events I posted I copied a previous event posting. None of them have a `category` entry. Also, the `README.md` file makes no mention of such a thing.

**Comment by mslinn** [comment]
... but thank you!

**Comment by SethTisue** [comment]
> None of them have a category entry

Your October event does. Remember https://github.com/scala/scala-lang/pull/484?

> the README.md file makes no mention of such a thing

Perhaps you are not viewing a current version? I'm looking at https://github.com/scala/scala-lang/blob/master/training/README.md and it's quite explicit about it.

**Comment by mslinn** [comment]
Seems that was [added to the docs 18 days ago](https://github.com/scala/scala-lang/commit/2a40f6f15c7329baff3b9cbb6656462e92b3bff9), when Andy fixed the bug that prevented my previous course listing from working

**Comment by heathermiller** [comment]
Sure. So it was in the README at the time you made this PR thanks to Andy's fix, no? Siding with Seth on this one.

In any case, the advertisement for your course is up, so all good on your side, right?

**Comment by mslinn** [comment]
All good

**Pull request merged**
