### PR TITLE
Adding quotations to event

### PR DESCRIPTION
**Pull request by heathermiller**

### CODE REVIEW

**Comment by SethTisue** [comment]
http://www.scala-lang.org/events/ looks OK even without this...?

**Comment by heathermiller** [comment]
You're right. Sorry for the noise then!

**Comment by andy1138** [comment]
As a little side note.
As far as I can tell, 'description' is not (currently) used for conference events so will not make that much difference. But think its a good idea to at least keep in a good format, I may even have a look to see if it can be used as a tooltip.
 
It is used in the js for training events however is not displayed.

**Comment by SethTisue** [comment]
okay!

**Pull request merged**
