### PR TITLE
Feature/sbtb training

### PR DESCRIPTION
**Pull request by boldradius**

### CODE REVIEW

**Comment by heathermiller** [comment]
Like in PR #301, the YAML front matter still does not appear to be correct.

**Comment by SethTisue** [comment]
@boldradius ...?

**Comment by SethTisue** [comment]
I tried DM'ing @boldradius on Twitter, but that didn't succeed in getting their attention. let me try @-mentioning @bwmcadams

**Comment by bwmcadams** [comment]
Let me raise this to the appropriate People In Charge.

**Comment by michaelpnash** [comment]
Got it! Will correct this, sorry we didn't see the notification. I can be reached at michael.nash@boldradius.com anytime.

Thanks!

**Comment by SethTisue** [comment]
closing for inactivity. can be reopened if needed.

**Pull request closed without merging**
