### PR TITLE
Add “ Best Scala Tutorials On YouTube” to community page

### PR DESCRIPTION
**Pull request by abhiphull**
Added a resource on Scala under "Community-Powered Learning Resources"

### CODE REVIEW

**Comment by SethTisue** [comment]
This doesn't look like a good resource to me — it's just a handful of links to individual talks? Seems really random

**Comment by abhiphull** [comment]
> This doesn't look like a good resource to me — it's just a handful of links to individual talks? Seems really random

Really appreciate your concern but these links are not randomly picked talks, these are all hands on tutorials where instructor is going through in detail about the Scala concepts. But let me know if you have any suggestions to make them more useful to the readers. I am more than happy to make necessary changes.

**Comment by exoego** [comment]
I think a curated list of online videos are good to have, only if the community can contribute to the list via GitHub or other content management systems.
Otherwise, such list may not reflect the voices from community.

The  suggested page seems just a personal blog page collecting random videos, and there seems no way to accept contributions from Scala community.

I suggest to create a dedicated page on  scala-lang.org, not on personal blogs/sites.

**Comment by SethTisue** [comment]
> these are all hands on tutorials where instructor is going through in detail about the Scala concepts

If that wasn't apparent to me, it probably won't be apparent to other readers, either. The page title, "Best Scala Videos on YouTube", doesn't communicate that.

There's also no indication of how long these videos are and whether it's just a single video or a whole series. And the titles give _some_ hints of which videos I might want to watch, but this would be more much helpful if there was more indication of what the intended audience of each video is. That's part of what I meant by “random” — for all I know you spent many hours and days selecting these videos and they aren't random at all, but the level of work you put into it isn't made apparent to the reader and isn't used to help the reader.

**Comment by abhiphull** [comment]
Thanks for your feedback and your suggestions totally make sense. I have tried to incorporate your suggestions by...

1. Adding more information about each video link
2. Also created a github repo for this blog and added a link to git on Scala page (at the bottom on https://www.nbshare.io/blog/best-scala-videos-on-youtube/) so that users can request any changes or additions.

Let me know what you think.

**Comment by SethTisue** [comment]
The main remaining issue here that I see is that:

* The title and URL of the resource remains misleading. As I wrote above, "The page title, "Best Scala Videos on YouTube", doesn't communicate" what the page is about.
* There isn't anything on the page itself that explains what it's for, what it's about. The title of page can only make a start at communicating that; the top of the page should communicate it further.
* You say you added a link to make it clear to contributors how they can submit additions, but I don't even see where that link is. The whole situation with regards to contributions should be clear _on the page itself_.

**Comment by abiphull** [comment]
Thanks for the valuable feedback.  
 I have changed the url and title to following...

-  https://www.nbshare.io/blog/best-scala-tutorials-on-youtube/ , Best Scala Tutorials On YouTube

-  Description about the page has been added to the top.
-  Also a link has been added about - "how to contribute" at the top of page.

**Comment by SethTisue** [comment]
Page looks good — now this PR needs updating to reflect to the new name and URL

**Comment by abhiphull** [comment]
Thanks I have submitted the PR again.

**Comment by SethTisue** [comment]
Thanks for being so accommodating of feedback :-)

**Pull request merged**
