### PR TITLE
Adds initial GSOC 2016 page

### PR DESCRIPTION
**Pull request by cvogt**
review by @sjrd or @VladUreche 

Wanted to add the Slick codegen project already

### CODE REVIEW

**Comment by VladUreche** [comment]
LGTM. Since I never merged into scala-lang, I'll let @heathermiller do it.

**Comment by SethTisue** [comment]
where will this be linked from?

**Comment by cvogt** [comment]
@SethTisue it was usually linked only from news entries and from the mailing list and twitter, etc if I am not mistaken

**Comment by cvogt** [comment]
in the old website there was a section for it, but not anymore. maybe should be under community?

**Comment by SethTisue** [comment]
yes, I think that would be appropriate

**Comment by cvogt** [comment]
Different target than this PR though :). Let's get this merged first.

**Pull request merged**
