### PR TITLE
GSoC proposal: REPL modernisation

### PR DESCRIPTION
**Pull request by marialivia16**
As per Adriaan's [suggestion](https://contributors.scala-lang.org/t/google-summer-of-code-2018-call-for-project-ideas/1483/2). I'd be interested to learn more about the REPL and also mentor a student if any interested.

### CODE REVIEW

**Comment by adriaanm** [comment]
Thank you for taking this on, @marialivia16!

**Comment by marialivia16** [comment]
@adriaanm I'm excited about this, thank you!

**Comment by som-snytt** [comment]
Now I'm definitely subscribing to the Guardian!

**Comment by retronym** [comment]
Assuming a JLine3 upgrade is part of this effort, it is worth subscribing to/reviewing recent archives of https://groups.google.com/forum/#!forum/jline-users. 

I've noticed a bunch of useful bug reports and upgrade tips that have stemmed from the work that @bdw429s has been [performing](https://github.com/Ortus-Solutions/commandbox/commits?author=bdw429s) over in CommandBox to do a JLine2 -> 3 upgrade.

**Comment by bdw429s** [comment]
Yes, I've bugged the heck out of poor Guillaume :)  He's quite responsive though and JLine3 is packed with new features and fixes so it's def worth an upgrade.

**Comment by adriaanm** [comment]
Btw, here are lots of interesting ideas on what makes for a nice repl: http://vvvvalvalval.github.io/posts/what-makes-a-good-repl.html

**Pull request merged**
