### PR TITLE
Fix #535: setup htmlproofer and fix all broken links

### LINKED ISSUE #535: automate broken link checking?
this could be part of the Travis build, using html-proofer or something like it

see #533, #534

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**

### CODE REVIEW

**Comment by SethTisue** [comment]
fantastic!!! thank you so much Olivier and @Philippus!

**Comment by jarrodwb** [comment]
Just a note on this. Travis will ping around 4624 links every time it runs. This will slow Travis down and also add a lot of extra traffic to these pinged links.

**Comment by ashawley** [comment]
> This will slow Travis down and also add a lot of extra traffic to these pinged links

So `--disable-external`?  Then someone can just check external locally every so often.

**Comment by jarrodwb** [comment]
That could work. We could test it out by making some new branches. I think Travis will pick up the new branches an run them. I am working on something else right now but I can swing by here when I am done.

**Comment by OlivierBlanvillain** [comment]
This repo had under 1k PR over the last 5 years, I'm sure that this is something web servers can handle. The [latest CI run](https://travis-ci.org/scala/scala-lang/builds/342373163) took ~25min out of which 10 were spent checking the links.

> So --disable-external? Then someone can just check external locally every so often.

htmlproof was already setup and ready to use for a very long time on docs.scala-lang.org which still had a huge amount of broken links (both external and internal). If having no broken link is something valuable, then checking it on every PR is the way to go!

**Comment by jarrodwb** [comment]
Can Travis be setup to check them every week? It seems like that kind of automation should be simple. I think Travis runs for every push to every branch in the repo and for every push to a branch that has an open PR. 

On my local system the time comparison was 19 seconds vs 86 seconds.

**Comment by ashawley** [comment]
> This repo had under 1k PR over the last 5 years

I believe Travis runs on every commit (well, pushed commit), including merges to master, and on forked repos for those who have it enabled.  There have been 2.5k commits in the last 5 years.  

> On my local system the time comparison was 19 seconds vs 86 seconds.

Comparison of what?

> Can Travis be setup to check them every week?

Does the site still run on an EPFL Jenkins to get published, or was that setup discontinued?

**Comment by jarrodwb** [comment]
```
htmlproofer ./_site/ --only-4xx --empty-alt-ignore --allow-hash-href --disable-external
htmlproofer ./_site/ --only-4xx --empty-alt-ignore --allow-hash-href
```

**Comment by ashawley** [comment]
> The times came from these two commands.

Oh, ok.  I thought it was taking 25 minutes to check bad links.  But if it's only a minute or, then I guess that Travis build was an outlier.

**Pull request merged**
