### PR TITLE
Added Discord and Gitter to socials in the footer of index

### PR DESCRIPTION
**Pull request by faith**
Title

### CODE REVIEW

**Comment by SethTisue** [comment]
ah, good idea! folks won't necessarily find the link through https://scala-lang.org/community/

but, as per https://github.com/scala/scala-lang/pull/1189 , Gitter remains our primary chat platform, though we're certainly experimenting with Discord as an alternate

so I don't think this is mergeable as-is. but I'd be happy to merge it if you added *both* Gitter and Discord, with Gitter first.

**Comment by faith** [comment]
> ah, good idea! folks won't necessarily find the link through https://scala-lang.org/community/
> 
> but, as per #1189 , Gitter remains our primary chat platform, though we're certainly experimenting with Discord as an alternate
> 
> so I don't think this is mergeable as-is. but I'd be happy to merge it if you added _both_ Gitter and Discord, with Gitter first.

Done. Added Gitter first as requested 👍

**Review by SethTisue — APPROVED** [review]

**Comment by faith** [comment]
Ups sorry for requesting the review again, didnt know what that button did 😆

**Comment by SethTisue** [comment]
Note that the footer already has a "Chat Rooms & More" link in the "Community" section (which links to https://scala-lang.org/community/index.html#chat-rooms)

So technically this addition might be considered redundant. I didn't realize that until after I hit merge.

Maybe it's fine regardless -- there is room in the footer. I don't have a strong feeling about it either way.

**Comment by faith** [comment]
Makes it easier to reach & find so why not i guess ¯\_(ツ)_/¯

**Pull request merged**
