### PR TITLE
get Gemfile in shape for 498

### PR DESCRIPTION
**Pull request by jarrodwb**
First shot at #498. It seems to build just fine.

I would be very interested in hearing about how the site is actually built and put on the server.

I think it would be just fine to build before it hits the server and just push the `_site` directory. This is how I push my site to S3. Then we would not need to worry about what is and is not installed on the server.

### CODE REVIEW

**Comment by jarrodwb** [comment]
lol. Now to take a look at the Jekyll file. :cry:

**Comment by jarrodwb** [comment]
Any hint on what version of Ruby to specify in the Travis file? I am fine with what we have in this PR but there maybe a better option.

**Comment by SethTisue** [comment]
review by @fsalvi?

**Comment by SethTisue** [comment]
> I would be very interested in hearing about how the site is actually built and put on the server.

I can't give a detailed account, but I do know there's a Jenkins job: https://scala-webapps.epfl.ch/jenkins/job/production_scala-lang.org-builder/

the script in the job config is:

```
#!/bin/bash -xe
echo "Hello."
echo "Workspace is: $WORKSPACE"
echo "Gems are in : $GEM_HOME"
echo "Path is : $PATH"
PATH="/data/scalaw3/local/gems/bin:/data/scalaw3/local/bin:$PATH"
export GEM_HOME="/data/scalaw3/local/gems"
/data/scalaw3/local/gems/bin/jekyll build
#--base-url=http://tresor-srv04.epfl.ch:8888/ 
rsync -avx "$WORKSPACE"/_site/ /data/scalaw3/local/htdocs --delete-after --exclude=/config.yml --exclude=/README.md --exclude=/WebDNA --exclude=/old --exclude=/.htaccess --exclude=/favicon.ico --exclude=/files --exclude=/404.html --exclude=/autoindexstyle.css --exclude=/autoindexheader.shtml
```

**Comment by jarrodwb** [comment]
After looking at the job config it seems like it would be pretty easy to add Bundler to the Jenkins job.

**Comment by heathermiller** [comment]
Pinging @fsalvi, can you get bundler set up so we can use it in the build?

**Comment by SethTisue** [comment]
> can you get bundler set up so we can use it in the build

omg that would be fantastic

**Comment by fsalvi** [comment]
Sorry, I'm on holidays this week far away with limited internet access. I'm not sure I will be able to look at it before Monday. I'll try to do it asap.

**Comment by SethTisue** [comment]
@fsalvi it can wait! enjoy

**Comment by fsalvi** [comment]
Ok, bundler is installed.

*** LOCAL GEMS ***
afm (0.2.2)
Ascii85 (1.0.2)
bigdecimal (1.2.8)
blankslate (3.1.3)
bundler (1.13.6)
classifier-reborn (2.0.4)
coderay (1.1.1)
coffee-script (2.4.1)
coffee-script-source (1.9.1.1)
colorator (0.1)
did_you_mean (1.0.0)
execjs (2.6.0)
fast-stemmer (1.0.2)
ffi (1.9.10)
hashery (2.1.1)
io-console (0.4.5)
jekyll (3.1.6)
jekyll-coffeescript (1.0.1)
jekyll-feed (0.3.1)
jekyll-gist (1.1.0)
jekyll-paginate (1.1.0)
jekyll-sass-converter (1.3.0)
jekyll-watch (1.3.0)
json (1.8.3)
kramdown (1.11.1, 1.10.0)
liquid (3.0.6)
listen (3.0.3)
mercenary (0.3.5)
mime-types (2.6.1)
minitest (5.8.4)
multi_json (1.11.2)
mysql (2.9.1)
net-telnet (0.1.1)
oj (2.12.10)
parslet (1.7.1)
pdf-core (0.5.1)
pdf-reader (1.4.0)
pg (0.18.4)
posix-spawn (0.3.11)
power_assert (0.2.7)
prawn (2.0.2)
prawn-table (0.2.1)
psych (2.0.17)
pygments.rb (0.6.3)
rake (10.5.0)
rb-inotify (0.9.7)
rdiscount (2.1.8)
rdoc (4.2.1)
redcarpet (3.3.4)
rouge (1.10.1)
ruby-rc4 (0.1.5)
safe_yaml (1.0.4)
sass (3.4.21)
sequel (4.32.0)
sequel_pg (1.6.14)
stringex (2.5.2)
test-unit (3.1.7)
toml (0.1.2)
ttfunk (1.4.0)
yajl-ruby (1.2.0)

**Comment by jarrodwb** [comment]
Great it looks like things got cleaned up. Thanks for all the help. :+1:

**Comment by jarrodwb** [comment]
The small change in the Travis file in this PR should fix Travis builds. It is currently failing for other more resent PR because Travis is using an older version on Ruby. #507 #510

**Comment by SethTisue** [comment]
thank you Fabien and Jarrod. really super to see this infrastructure type stuff gradually getting straightened out and modernized

**Pull request merged**
