### PR TITLE
use caching for faster Travis builds

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by sjrd** [comment]
```
store build cache
$ bundle clean
0.00s1.26schanges detected, packing new archive
FAILED: tar -Pzcf /home/travis/.casher/push.tgz 
tar: Cowardly refusing to create an empty archive
Try `tar --help' or `tar --usage' for more information.
uploading archive
failed to upload cache
curl: Can't open '/home/travis/.casher/push.tgz'!
curl: try 'curl --help' or 'curl --manual' for more information
```
Note the big FAILED and later "failed to upload cache" ...

**Comment by SethTisue** [comment]
hmm, maybe because 66c578540f5f203a9898736558d5a74e625d951e

**Comment by SethTisue** [comment]
:scream:

**Comment by SethTisue** [comment]
well I had hit rebuild before without the problem going away, but I tried hitting rebuild again, and this time it worked. so let's be optimistic and assume it was some transient problem.

**Pull request merged**
