### PR TITLE
Add new BoldRadius training course schedule

### PR DESCRIPTION
**Pull request by boldradius**
Please find included our new schedule for training courses through to the end of this year.

Thanks!

### CODE REVIEW

**Comment by heathermiller** [comment]
Awesome! LGTM!

**Comment by heathermiller** [comment]
Actually – I'm not certain that this will work. Usually you need this a starting and ending `---` to make this a YAML front matter as in other entries: https://github.com/scala/scala-lang/blob/master/training/_posts/2015-03-30-advanced-scala.html

**Comment by SethTisue** [comment]
paging @boldradius ?

**Comment by SethTisue** [comment]
appears superseded by #318

**Pull request closed without merging**
