### PR TITLE
Scaladex autocomplete

### PR DESCRIPTION
**Pull request by MasseGuillaume**
auto

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
when we find the missing sass this is the style: 


```
.autocomplete-suggestions {
    width: 100%;
    background: #fff;
    top: 42px;
    left: 0;
    position: absolute;
    z-index: 9999;
    -webkit-box-shadow: 0 2px 20px rgba(0, 0, 0, 0.2);
    box-shadow: 0 2px 20px rgba(0, 0, 0, 0.2);
}

.autocomplete-suggestions {
    padding: 0;
    margin: 0;
}

.autocomplete-suggestions .autocomplete-suggestion {
    padding: 15px;
    list-style: none;
    border-bottom: 1px solid rgba(0, 43, 55, 0.1);
}

.autocomplete-suggestions .autocomplete-suggestion:last-child {
    border-bottom: none;
}

.autocomplete-suggestions .autocomplete-suggestion a {
    color: #586e75;
}

.autocomplete-suggestions .autocomplete-suggestion a:hover,
.autocomplete-suggestions .autocomplete-suggestion a:active,
.autocomplete-suggestions .autocomplete-suggestion a:focus {
    text-decoration: none;
}

.autocomplete-suggestions .autocomplete-suggestion a p {
    color: #224951;
    margin: 0;
    font-weight: 400;
}

.autocomplete-suggestions .autocomplete-suggestion:hover,
.autocomplete-suggestions .autocomplete-suggestion.selected {
    background: #edf1f1;
    cursor: default;
}
```

**Comment by heathermiller** [comment]
Could you explain what you did with style.css?

**Comment by heathermiller** [comment]
Ok, so this actually shouldn't be merged with the changes to style.css I take it.

**Comment by heathermiller** [comment]
#685

**Comment by MasseGuillaume** [comment]
@heathermiller rebased, this is good to go.

**Comment by heathermiller** [comment]
Thanks, but this is still not working.

For example, type in cats. Nothing is found in the dropdown. That's OK, we can just go to Scaladex, right? Wrong. Pressing enter after typing cats does nothing. 

So this still needs to be fixed.

**Comment by MasseGuillaume** [comment]
@heathermiller good to go.

**Comment by heathermiller** [comment]
Perfect! Thank you!

**Pull request merged**
