### PR TITLE
Fix URLs to Jenkins jobs in README

### PR DESCRIPTION
**Pull request by ashawley**

### CODE REVIEW

**Comment by jarrodwb** [comment]
Looking at the Travis checks it looks like the Ruby version should be stated in either the Gemfile or the Travis file. My bet is the Gemfile.

What version of Ruby is installed in production?
@SethTisue

**Comment by ashawley** [comment]
@jarrodwb Probably using 2.2 for Travis is as good a guess as any.  So you did just that in 02c2e3c of #499

**Comment by SethTisue** [comment]
@jarrodwb I'm baffled by this Ruby version issue. can you open a separate ticket on it?

**Comment by SethTisue** [comment]
oh, I see now the Ruby thing is under discussion at https://github.com/scala/scala-lang/pull/499

**Pull request merged**
