### PR TITLE
Small tidyup of events page

### PR DESCRIPTION
**Pull request by propensive**
Generally display the event locations in a consistent format, with consistent names.

### CODE REVIEW

**Comment by heathermiller** [comment]
Thanks Jon! My only worry though is that some of these expanded location fields might not fit nicely in the little event box. Merging to see :)

**Comment by propensive** [comment]
Yeah, that was a problem both before and after, unless you have small fonts... I did have a go at improving it, but it wasn't a five-minute job. :(

**Comment by heathermiller** [comment]
It's OK. It doesn't look particularly bad or anything. Thanks for the update!

**Comment by propensive** [comment]
No problem. This page is my personal diary - I care about it! ;)

**Comment by heathermiller** [comment]
Haha, true. Hey @SethTisue, I think we found a permanent maintainer for the events page!! 
yes-napoleon

**Comment by propensive** [comment]
More than happy to do that. I was also discussing with a couple of conference organizers last year the possibility of having more coordination over conference dates before they're announced... We've got another clash again in April which means I can't go to both Kyiv and Warsaw... :(

**Comment by andy1138** [comment]
I was adding the events even I found then, but Jon is probably more
suited (given he goes to most of them) so will let him do it.

As for town names, location. I've always kept it to how the event
wants to describe it, if one is 'Cracow' and the other 'Kraków' then I
don't know what is the correct spelling. (and to be honest not 100%
that they are the same place).  The same applies to State etc, if a
conference think everybody New York is then I want going to change
things (or look them up if I didn't know)

If the locations are made consistent then maybe a little google map is
in order :-)


On 6 January 2017 at 10:15, Jon Pretty <notifications@github.com> wrote:
> More than happy to do that. I was also discussing with a couple of
> conference organizers last year the possibility of having more coordination
> over conference dates before they're announced... We've got another clash
> again in April which means I can't go to both Kyiv and Warsaw... :(
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tanis Systems Limited is a company registered in England and Wales.
Registered number: 5464771. Registered office: 2 Avondale House, 264
Croydon Road, Caterham, CR3 6QJ, VAT 238866167

**Comment by SethTisue** [comment]
thanks for your help with this in recent months, Andy. Jon, pleased you'd like to take this on.

**Comment by heathermiller** [comment]
Hey @andy1138, yes I echo @SethTisue! Thank you very much for helping to keep this updated! 

And thank you very much @propensive!

**Comment by SethTisue** [comment]
@propensive according to https://twitter.com/beescalaconf BeeScala dates are set for November

**Pull request merged**
