### PR TITLE
blog post summarizing recent meetings

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
review by @heathermiller and/or @jvican

**Comment by jvican** [comment]
Hey Seth, thanks a lot for preparing this! I like it because it goes to the point :smile:.

**Comment by SethTisue** [comment]
tweeted https://twitter.com/scala_lang/status/809056601130684416

**Comment by heathermiller** [comment]
🎉 Merci!

**Pull request merged**
