### PR TITLE
New blog post on Dotty bootstrap

### PR DESCRIPTION
**Pull request by odersky**

### CODE REVIEW

**Comment by xeno-by** [comment]
\o/

**Comment by smarter** [comment]
It might be time to update the README too: https://github.com/lampepfl/dotty/blob/master/README.md

**Comment by adriaanm** [comment]
Congrats!

**Comment by SethTisue** [comment]
should the "Join the team of contributors" part list @DarkDimius explicitly? His name is on the blog post, but that's easy for folks not to notice. For folks who follow Dotty even a little it goes without saying, but lots of Scala people don't know Dmitry yet.

**Comment by odersky** [comment]
On Fri, Oct 23, 2015 at 4:51 PM, Adriaan Moors <notifications@github.com>
wrote:

> Congrats!
>

Thanks! - Martin


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scala/scala-lang/pull/341#issuecomment-150596484>.
>



-- 
Martin Odersky
EPFL and Typesafe

**Comment by odersky** [comment]
@DarkDimius, do you want to be mentioned under "team of contributors"? If
yes, can you add yourself?


On Fri, Oct 23, 2015 at 4:54 PM, Seth Tisue <notifications@github.com>
wrote:

> should the "Join the team of contributors" part list @DarkDimius
> <https://github.com/DarkDimius> explicitly? His name is on the blog post,
> but that's easy for folks not to notice. For folks who follow Dotty even a
> little it goes without saying, but lots of Scala people don't know Dmitry
> yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scala/scala-lang/pull/341#issuecomment-150597368>.
>



-- 
Martin Odersky
EPFL and Typesafe

**Comment by DarkDimius** [comment]
@odersky I'd like to.
Though I can't add myself as I do not have write access to
https://github.com/odersky/scala-lang/

**Comment by odersky** [comment]
Ok, I'll do it.

On Fri, Oct 23, 2015 at 5:01 PM, Dmitry Petrashko <notifications@github.com>
wrote:

> @odersky <https://github.com/odersky> I'd like to.
> Though I can't add myself as I do not have write access to
> https://github.com/odersky/scala-lang/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scala/scala-lang/pull/341#issuecomment-150599926>.
>



-- 
Martin Odersky
EPFL and Typesafe

**Pull request merged**
