### PR TITLE
Adding Scala workshops 

### PR DESCRIPTION
**Pull request by SalasSanchez**
These files add two workshops happening right before LamdbaConf 2017.
http://lambdaconf.us/training/lcusc/mastering-apache-spark.html
http://lambdaconf.us/training/lcusc/advanced-functional-programming-with-scala.html

### CODE REVIEW

**Comment by heathermiller** [comment]
LGTM, thanks!

**Comment by SethTisue** [comment]
I've reverted this because this is training, not conferences.

feel free to submit a new PR adding these to the `training` directory, not the `events` directory, so they show up at http://www.scala-lang.org/training/

**Comment by SalasSanchez** [comment]
Ah, duh. Ok. I will. Thanks!

**Comment by heathermiller** [comment]
Oh oops. Sorry @SethTisue! I pushed merge too quickly on this one. Thanks for catching it :)

**Pull request merged**
