### PR TITLE
Remove develepment version from footer

### PR DESCRIPTION
**Pull request by jarrodwb**
fix for #532 

Also note that I changed Stable to Current. I can change this back or to something else people prefer.

### CODE REVIEW

**Comment by SethTisue** [comment]
I didn't have this idea until just now, but what do you think about replacing "Development version" with an "All versions" link that goes to http://www.scala-lang.org/download/all.html ?

**Comment by jarrodwb** [comment]
Hey Seth. Yeah I can do that. Probably tomorrow though. :-)

**Comment by jarrodwb** [comment]
We now have "Current Version" and "All Versions" in the footer.

I also ran `grep -r site.devscalaversion .` and did not get any hits. I think we are ready to go with this.

**Comment by heathermiller** [comment]
LGTM! :)

**Comment by heathermiller** [comment]
Thanks @jarrodwb!

**Pull request merged**
