### PR TITLE
Add spp blog post

### PR DESCRIPTION
**Pull request by jvican**
This is the blog announcing the draft of the Scala Platform and the Scala Platform process.

### CODE REVIEW

**Comment by heathermiller** [comment]
LGTM!

**Comment by SethTisue** [comment]
It doesn't say "SLIP" anywhere. I think some people might be left confused about whether this replaces the SLIP process, or what?

**Comment by jvican** [comment]
Just for the record, SPP is the new "SLIP".

**Comment by SethTisue** [comment]
thanks.

how about the reference to the committee being "elected" — is that a typo for "selected"?

**Comment by jvican** [comment]
No, I used it based on the first definition of Merriam Webster: http://www.merriam-webster.com/dictionary/elect. Does this word connote something bad?

**Comment by SethTisue** [comment]
that's "elect", the adjective.

But you used the verb. English is weird. I can "elect" to do something; that is simply choosing, not voting. But if I say someone was "elected", that definitely means voting happened.

**Comment by SethTisue** [comment]
I fixed it in 6e83ea6ef3a4578e890c4529580062db44531360

**Comment by jvican** [comment]
Thanks @SethTisue

**Pull request merged**
