### PR TITLE
2.11.5

### PR DESCRIPTION
**Pull request by adriaanm**

### CODE REVIEW

**Comment by sjrd** [comment]
LGTM

**Comment by adriaanm** [comment]
Generated by https://github.com/scala/make-release-notes/pull/134

```
$ sbt -Dfile.encoding=UTF-8 console 

Welcome to Scala version 2.11.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_25).
Type in expressions to have them evaluated.
Type :help for more information.

scala> MakeReleaseNotes.genPR("2.11.4", "2.11.5", "2015/01/14")
```

**Comment by adriaanm** [comment]
Thanks!

**Comment by adriaanm** [comment]
Shall I hit the green button?

**Comment by heathermiller** [comment]
Yup, go ahead :)

**Comment by adriaanm** [comment]
Thanks!

**Comment by adriaanm** [comment]
Ugh, looks like I angered Maruku. Maruku tells you: fail!
Looking into it.

**Pull request merged**
