### PR TITLE
Past events should be available #519

### PR DESCRIPTION
**Pull request by lucianenache**
This pull request adds the past events page into the new layout proposed by #606 adding also the missing logos of some past events.  

Additionally a small bug with events displayed wrong in the main page has been fixed (event.date was used for filtering instead of event.start).

I have a small issue on where the past events link should be placed on the events page and also a pagination issue where some pages are just empty. Help would be appreciated

### CODE REVIEW

**Comment by SethTisue** [comment]
(I won't be able to help review this until late June — if anyone else can step up to help Lucian with this sooner, please do)

**Comment by jarrodwb** [comment]
I can take a closer look a this and also the repo as a whole when I get back to Hamburg. Cheers :-)

**Comment by lucianenache** [comment]
Awesome, I would like to add two things sometime this week:

- Add logos provided as URLs to the repository as static images
- Add a pagination template for the past events page
- Make a decent visible link to the past events page

The current pagination template used for current events is not suited for the past events page, therefore it should get it's own template.

**Comment by heathermiller** [comment]
Just a heads up that I'm also not going to be able to help review this for the next 1-2 weeks. If anyone else is interested, we'd love the help! ❤️

**Comment by jarrodwb** [comment]
I am starting to get into this again. I am just wondering on if #606 is a blocker.

**Comment by jvican** [comment]
Not an expert here, but I would try to merge this PR and forget about the previous one (it seems it has been abandoned). It seems that @lucianenache does address important issues here. @heathermiller and @SethTisue could perhaps confirm? :smile:

**Comment by lucianenache** [comment]
The initial purpose of this PR was to be merged into #606 once that was reviewed, we could spin off from here if necessary even though I am not sure how we should move for the things that should be addressed in #606

**Comment by SethTisue** [comment]
I guess we just need to wait on this until #606 or #667 is merged

**Comment by lucianenache** [comment]
That is fine since at least this week and the beginning of the next I have limited availability to contribute to the missing features

**Comment by SethTisue** [comment]
#606 and #667 are merged. is someone interested in resurrecting this, now?

**Comment by heathermiller** [comment]
Ah yes, thanks for reopening this! ❤️ If anyone would like to rebase this and get it over the finish line, we're super happy to merge :)

**Comment by lucianenache** [comment]
Hi guys, I have already forgot about this and been super busy with work. Over the next week I might have the time to pick off from where I was left and finish it.

**Comment by heathermiller** [comment]
❤️

**Comment by lucianenache** [comment]
Hi guys, sorry for the delay but in the past weeks been very busy with work then my machine broke down and finally had an akka pr that I took care of. So the pagination of past events looks good to me.

I have rebased from master and added the missing functionality.

Given the initial todo list here is the status:

 - [X] Add logos provided as URLs to the repository as static images
 - [] Add a pagination template for the past events page (excluded)
 - [X] Make a decent visible link to the past events page

Currently all past events are loaded in the same page, if we want to add pagination, we should create a custom paginator and different template and maybe display that by year (the current paginator breaks and splits months over multiple pages)

**Comment by lucianenache** [comment]
@heathermiller & @SethTisue  let me know in case I have missed anything and whether the current visualization makes sense

**Comment by heathermiller** [comment]
This looks great, @lucianenache! Thank you! ❤️

**Comment by SethTisue** [comment]
this is super! I'm really happy to have this resolved. thank you Lucian

we can always tweak the visuals further, now that the hard part is done.

I don't think pagination is necessary.

**Comment by heathermiller** [comment]
Little tweaks here: c233ff02bd85b2fa1412c18dcd94a3994020ab7a
😊

**Comment by lucianenache** [comment]
Thanks, I'll continue helping as time allows :)

**Pull request merged**
