### PR TITLE
change "Get Started" button text

### PR DESCRIPTION
**Pull request by bishabosha**
Change to "Setup Scala"

people seem to be confused at the choice of "Get Started" and "Learn Scala", here's one option to try:

Screenshot 2022-12-20 at 12 58 12

the other option could be to change the text of "Learn Scala" to something else

### CODE REVIEW

**Comment by sjrd** [comment]
TBH I think "Get Started" was the better one, and "Learn Scala" should be changed instead. Perhaps to "Reference documentation" or something like that.

**Comment by julienrf** [comment]
> people seem to be confused at the choice of "Get Started" and "Learn Scala"

Where? Do you have examples?

I am not sure about the proposed change. If someone needs to be changed, maybe “learn Scala” could be replaced with “documentation”?

**Comment by bishabosha** [comment]
> Where? Do you have examples?

every time I ask someone in person what they think this happens to me :) but that is still anecdotal

**Comment by bishabosha** [comment]
something like this?

Screenshot 2022-12-20 at 15 23 10

**Comment by julienrf** [comment]
It would be good to ask the same people who were confused about the current structure.

**Comment by SethTisue** [comment]
"setup" isn't a verb — it's “set up”

**Comment by bishabosha** [comment]
superseded by #1518

**Pull request closed without merging**
