### PR TITLE
WIP: Do not merge: Add TODO

### PR DESCRIPTION
**Pull request by janekdb**
*TODO*
- [ ] Move these notes to an issue and close this PR 
- [ ] Build documentation locally
- [x] Clone `scala/scala.github.com` as this is where the overviews and tutorial reside
- [x] Delete `TODO.txt`
- [x] Add links to @VladUreche document
- [x] Move PR to new repo
- [ ] Locate diagrams suggested by Vlad gist
- [ ] Outline structure
- [ ] Pick up content from old wiki
- [ ] Add `hideImplicitConversion` to Scaladoc tutorial
- [ ] Document @shortDescription
- [ ] Document @group tags
- [ ] Document @hideImplicitConversion
- [ ] Document @shortDescription using https://github.com/scala/scala/pull/4991/files as an guide to an example
- [ ] Document @documentable
- [ ] Describe all @contentDiagram specifiers

### CODE REVIEW

**Comment by janekdb** [comment]
@VladUreche - you mentioned some documents and diagrams you had about Scaladoc links. Can you share links?

**Comment by VladUreche** [comment]
Hi @janekdb, sorry for the late answer. This is the documentation I started to write a very long time ago: https://gist.github.com/VladUreche/7eca3c83cdadd1076889

**Comment by janekdb** [comment]
Many thanks!

**Comment by SethTisue** [comment]
provisionally closing for lack of recent activity. can always be reopened

**Pull request closed without merging**
