### PR TITLE
amabassador (Salar Rahmanian) added more contact options

### PR DESCRIPTION
**Pull request by softinio**

### CODE REVIEW

**Comment by softinio** [comment]
cc @SethTisue thanks 🙏

**Comment by SethTisue** [comment]
@softinio may I suggest that you also include a link to Scala News?

**Comment by softinio** [comment]
@SethTisue Good idea! Assume just include it as part of my bio part in the yaml? 

I can also add my matrix if you think useful. Is there an icon for it for me to add like GitHub/mastodon etc or include as part of bio? I can skip adding this if getting too cluttered.

**Comment by SethTisue** [comment]
link in bio: yes please

matrix: not sure, won’t have time to check on it this week, but I’ll reply next week

**Comment by softinio** [comment]
@SethTisue done! Here you go: https://github.com/scala/scala-lang/pull/1637

**Pull request merged**
