### PR TITLE
Fix training feed

### LINKED ISSUE #698: Training feed on front page broken

### PR DESCRIPTION
**Pull request by ashawley**
Fixes #698 

I don't think the training feed is broken, but I've added an upcoming training to prove it still works, and updated the README while I was at it.

### CODE REVIEW

**Comment by SethTisue** [comment]
thanks!

**Comment by heathermiller** [comment]
Thanks.

The issue seems to be fetching from Lightbend's training feed... I haven't had the time to look into it, but this is still "broken" in that we're not getting events from Lightbend.

**Comment by SethTisue** [comment]
I'll let somebody at Lightbend know

**Comment by SethTisue** [comment]
fixed in 35c0bb2143247f35c051239fd88ad994c39583eb

**Comment by heathermiller** [comment]
Call me crazy, but it still seems broken to me. None of those feeds from the Lightbend training feed seem to be coming through: 
screen shot 2017-10-04 at 8 56 00 am

**Comment by SethTisue** [comment]
let's continue on #698

**Pull request merged**
