### PR TITLE
Community - Russian-speaking chat room

### PR DESCRIPTION
**Pull request by dos65**
It's a large chat room (1k+ members)

### CODE REVIEW

**Comment by propensive** [comment]
Thank you, @dos65!

**Comment by SethTisue** [comment]
fixup in 2009607d3fd71b13d5734f8116ce9ed29a2dc2a6

**Comment by SethTisue** [comment]
(I think it's better to collect the non-English-rooms together, rather than to have the primary grouping be by protocol)

**Comment by propensive** [comment]
Agreed, thanks @SethTisue!

**Pull request merged**
