### PR TITLE
Update Community Resources

### PR DESCRIPTION
**Pull request by adamgfraser**
Add ZIO and Zymposium to community resources.

### CODE REVIEW

**Comment by SethTisue** [comment]
Of the three changes here, 1 and 3 look mergeable to me. I don't think the second change fits; it's a list of learning resources that are focused on the Scala language itself, and I don't think we want to broaden the scope beyond that.

**Comment by adamgfraser** [comment]
I'm not sure what it means for a learning resource to be "focused on the Scala language itself".

Zymposium covers a variety of topics in Scala including use of specific language features as well how to use different libraries to solve various problems in Scala. For example:

* [Zymposium - Variance](https://www.youtube.com/watch?v=2uEjXuFBsBk&list=PLvdARMfvom9C8ss18he1P5vOcogawm5uC&index=12)
* [Zymposium — Path Dependent Types](https://www.youtube.com/watch?v=w2rcHCqdn-o&list=PLvdARMfvom9C8ss18he1P5vOcogawm5uC&index=19)
* [Zymposium — Type-Level Sets](https://www.youtube.com/watch?v=N_it0qwk7_U&list=PLvdARMfvom9C8ss18he1P5vOcogawm5uC&index=18)
* [Declarative vs Executable Encodings](https://www.youtube.com/watch?v=OD1Yr48-0Js&list=PLvdARMfvom9C8ss18he1P5vOcogawm5uC&index=27)
* [Zymposium - Caliban](https://www.youtube.com/watch?v=mzqsXklbmfM&list=PLvdARMfvom9C8ss18he1P5vOcogawm5uC&index=11)

I suppose it would be possible to have a principle that these learning resources should be focused exclusively on language features and not rely on any libraries outside the standard library. If so would be happy to update the PR to delete the reference to Zymposium as well as other learning references that are not focused on the Scala language itself, such as Scala Exercises, which includes materials on a variety of libraries outside the Scala standard library such as Cats, Shapeless, Doobie, ScalaCheck, Circe, Fetch, and Monocle.

Alternatively, I would tend to think that one of the great things about Scala is that there are a lot of awesome libraries written in Scala that allow you to solve a variety of problems that cannot and should not be expected to be solved with the standard library alone, such as standing up a web service. In this case learning resources would cover materials that focus on specific language features as well as how to solve various problems in Scala, which would necessarily include discussion of libraries appropriate to solve those problems.

Let me know which direction you would like to go.

**Comment by SethTisue** [comment]
I'd suggest you drop the Zymposium link from this PR so then the rest can be promptly merged without further discussion.

Then the Zymposium thing could go in a separate PR and we can see what somebody from the Scala Center thinks, perhaps.

**Comment by SethTisue** [comment]
(closing for inactivity, as is customary here; we can reopen if activity resumes)

**Pull request closed without merging**
