### PR TITLE
Upgrade jekyll to version 3.8.5

### PR DESCRIPTION
**Pull request by RichardMarto**
This PR comes to solve #973.
I just followed the same path as #940 and I got similar results.

### CODE REVIEW

**Comment by SethTisue** [comment]
looks like `.travis.yml` needs a change?

```
3.94s$ bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
You must use Bundler 2 or greater with this lockfile.
```

**Comment by SethTisue** [comment]
I'm a Ruby/rvm/bundler idiot, but maybe https://github.com/scala/scala/pull/7599 is relevant here as a model?

**Comment by RichardMarto** [comment]
> Two things:
> 
> 1. Try removing the "BUNDLED WITH" section of the `Gemfile.lock` so that building the site doesn't depend on a particular version of bundler, but also fixes the Travis error Seth mentioned.
> 2. Change the value for `rvm` from "2.3.1" to be `2.4` in `.travis.yml`, since Travis enables Bundler 2.0 with 2.4 or later, since one wants to transition to Bundler 2.0.
> 
> I suppose we only need to do (1), but might as well do both.

It worked, I just did the first trick, thanks.

**Comment by SethTisue** [comment]
@ashawley shall we merge?

**Comment by ashawley** [comment]
This means the bundler required is version 1.x, still.  This may need to be documented in the README.   It's also unfortunate that running `bundle install` will modify `Gemfile.lock`, so people have to annoyingly ignore its change when committing to git.   This is where we're at with multiple major versions of bundler.

**Comment by propensive** [comment]
@ashawley If I'm understanding your comment correctly, I think we can document our way past annoying log messages. If that's all we need, can I give this a gentle nudge towards being merged? My understanding of the domain is certainly inferior to @SethTisue's, so I think all we need is just a brief confirmation that it's safe to merge. :)

**Comment by SethTisue** [comment]
thanks @RichardMarto and reviewers!

**Pull request merged**
