### PR TITLE
Create 2021-02-13-scalaloveinthecity2021.md

### PR DESCRIPTION
**Pull request by idabzo**

### CODE REVIEW

**Comment by SethTisue** [comment]
the `logo:` can't be a URL, it must be a file in the repo. 2020-04-18-scala-love.md has `logo: /resources/img/scalalove.png` — if you want a special "Scala Love in the City" logo instead, you need to include the file in the PR (in both regular and `@2x` versions)

for the link, https would be preferable to http, I think

**Comment by SethTisue** [comment]
you've updated the `logo:` line to refer to a file that doesn't exist. you either need to use an existing file, or include the new file in the pull request

**Review by Philippus — APPROVED** [review]
❤️ thank you!

**Comment by SethTisue** [comment]
283aa0dc821749252ca771f6ed3d159461bbe4aa replaces http with https

**Pull request merged**
