### PR TITLE
Add Scala Native Gitter channel

### PR DESCRIPTION
**Pull request by byeonggukgong**
Add Scala Native Gitter channel in `_data/chats-forums.yml` and `community/index.md`.

Refs: scala/docs.scala-lang#1139
Closes: scala/docs.scala-lang#1139

### CODE REVIEW

**Comment by byeonggukgong** [comment]
@NthPortal I squashed them into one. Please check the PR is okay :)

**Comment by byeonggukgong** [comment]
@NthPortal @Philippus I don't know what Gitter channel is most activated exactly, so I can't ranked the Gitter channels. I think It's good for members to decide.

**Comment by NthPortal** [comment]
Showing another channel would probably be preferable, but I'm not sure what other channel to add

**Comment by SethTisue** [comment]
> but I'm not sure what other channel to add

I'd suggest lampepfl/dotty

it should also be added in the "Chat Rooms" section farther down on the same page

**Pull request closed without merging**
