### PR TITLE
Correct a date for ScalaSphere

### PR DESCRIPTION
**Pull request by mpociecha**
There's another day (workshops, hackathons) before the conference itself which we count as an integral part of a whole event.

### CODE REVIEW

**Comment by mpociecha** [comment]
The build failure looks unrelated

```
- ./_site/blog/2016/07/20/sip-summary-minutes.html
  *  External link http://docs.scala-lang.org/sips/pending/async.html failed: 404 No error
  *  External link http://docs.scala-lang.org/sips/pending/trait-parameters.html failed: 404 No error
- ./_site/blog/2016/08/15/sip-meeting-august-results.html
  *  External link http://docs.scala-lang.org/sips/pending/42.type.html failed: 404 No error
  *  External link http://docs.scala-lang.org/sips/pending/repeated-byname.html failed: 404 No error
  *  External link http://docs.scala-lang.org/sips/pending/spores.html failed: 404 No error
- ./_site/news/2.10.4/index.html
  *  External link http://docs.scala-lang.org/sips/pending/implicit-classes.html failed: 404 No error
  *  External link http://docs.scala-lang.org/sips/pending/modularizing-language-features.html failed: 404 No error
  *  External link http://docs.scala-lang.org/sips/pending/type-dynamic.html failed: 404 No error
- ./_site/news/2.12-roadmap/index.html
  *  External link http://docs.scala-lang.org/sips/pending/improved-lazy-val-initialization.html failed: 404 No error
htmlproofer 3.8.0 | Error:  HTML-Proofer found 9 failures!
```

**Comment by propensive** [comment]
Yes, I'm not sure what's going on with the builds, but the errors are unrelated.

**Comment by Philippus** [comment]
maybe related to @adriaanm's changes for https://github.com/scala/docs.scala-lang/issues/872 ?

**Comment by propensive** [comment]
Sounds like a reasonable explanation! I don't have time to fix it, so any assistance would be very welcome! (And I haven't overlooked the fact you've been very helpful here before, @Philippus!)

**Pull request merged**
