### PR TITLE
Update an example in Java

### PR DESCRIPTION
**Pull request by som-snytt**
Update the example to be more plausible yet no less pitiable.

### CODE REVIEW

**Comment by SethTisue** [comment]
maybe include both the old and new styles? or old-style only but identify it as "Java (pre Java 8)" or something? a lot of Java programmers are still writing in the old style, and the same is true of other languages. showing how the code looks in imperative style is arguably more important than showing how it looks with an only rather superficially different Java API

**Comment by SethTisue** [comment]
@som-snytt wdyt?

**Comment by som-snytt** [comment]
Life was too short.

**Comment by SethTisue** [comment]
more time to work on that JLine 3 PR 🤩

**Pull request closed without merging**
