### PR TITLE
Add reddit.com/r/scala to community page

### PR DESCRIPTION
**Pull request by joshlemer**

### CODE REVIEW

**Comment by SethTisue** [comment]
I may be nitpicking here, but "large and active" seems like an exaggeration to me, honestly. How about "active"?

**Comment by joshlemer** [comment]
Really? /r/Scala has 10k readers, around [2k unique visitors a](https://www.reddit.com/r/scala/about/traffic/), and [is one of the biggest programming language subreddits](https://www.reddit.com/r/programming/wiki/faq#wiki_what_language_reddits_are_there.3F).

**Comment by SethTisue** [comment]
ok, I'm convinced. I was just looking at the vote and comment numbers.

**Comment by joshlemer** [comment]
Cheers! :+1:

**Comment by heathermiller** [comment]
Thanks @joshlemer! Totally agree. I find myself on the Scala subreddit pretty often. Great idea to include it :)

**Pull request merged**
