### PR TITLE
Add minutes for Sept 2015 meeting to blog

### PR DESCRIPTION
**Pull request by dickwall**

### CODE REVIEW

**Comment by sjrd** [comment]
LGTM

**Comment by SethTisue** [comment]
next time please merge it 2 minutes *before* Dick posts it, ok Sébastien? ;-)

**Comment by SethTisue** [comment]
next time please merge it 2 minutes *before* Dick posts it, ok Sébastien? ;-)

**Comment by sjrd** [comment]
Sorry, what did I do wrong? Post it where? I had no idea this was not ok to merge.

In general, if you don't want a PR to be merged just yet (but only open it for review or so), please make it clear in the description of the PR (or better, its title) with something like "DO NOT MERGE YET". That helps avoiding that kind of mistakes.

**Comment by SethTisue** [comment]
no worries, only kidding.

**Pull request merged**
