### PR TITLE
Add event flatmap(oslo)2017 fix and scalawave

### PR DESCRIPTION
**Pull request by andy1138**

### CODE REVIEW

**Comment by heathermiller** [comment]
LGTM! :)

**Comment by SethTisue** [comment]
neither event is showing up at http://www.scala-lang.org/events/ ?

**Comment by andy1138** [comment]
@heathermiller @SethTisue   
Assuming I'm looking at the correct Jenkins build ( https://scala-webapps.epfl.ch/jenkins/job/production_scala-lang.org-builder/ ). 

It looks like scala-lang updates has been broken for the last couple of days.  Something to do with 'Could not find 'liquid' (~> 3.0)'  but my jekyll foo isn't very good to say why.

**Comment by SethTisue** [comment]
@fsalvi is this your dept...?

**Comment by fsalvi** [comment]
It's fixed now. Some ruby packages were automatically removed by mistake on the server... Sorry about that.

**Comment by SethTisue** [comment]
cool, thanks Fabien!

**Pull request merged**
