### PR TITLE
Bagwell 2018 and 2019 winners

### PR DESCRIPTION
**Pull request by SethTisue**
marking as "draft" until there's a blog post or two to link to

/cc @jsuereth @darjutak @sjrd

### CODE REVIEW

**Comment by SethTisue** [comment]
ping

**Comment by SethTisue** [comment]
ping

**Comment by SethTisue** [comment]
presumably this is on hold until Darja is back from vacation

**Comment by darjutak** [comment]
Darja is back, writing up blogs today - will need your input (list of achievements).
Thank you for pinging us patiently!

**Pull request merged**
