### PR TITLE
Fix events and training links

### LINKED ISSUE #91: Middle-clicking broken in some places
Middle-clicking items under "upcoming events" and "upcoming training" does nothing.

Middle-clicking `@usernames`, `#bugnumbers` and some ordinary-looking links under "What's new" opens them in the current tab.

### PR DESCRIPTION
**Pull request by julienrf**
Fixes #91

### CODE REVIEW

**Comment by julienrf** [comment]
Is there a pre-production instance of the scala-lang site?
I was not able to fetch “ajax” events and training, so comparing what I have with this PR with what is currently displayed by scala-lang.org was not possible.

**Comment by heathermiller** [comment]
Nope, no pre-production instance of the scala-lang site. For the events, we've just been merging and hotfixing if we eventually notice an issue :.

**Comment by heathermiller** [comment]
cc/ @retronym (merge away if this looks good to you!)

**Comment by retronym** [comment]
LGTM

**Pull request merged**
