### PR TITLE
add lambdaconf 2016 event

### PR DESCRIPTION
**Pull request by jdegoes**

### CODE REVIEW

**Comment by SethTisue** [comment]
lambdaconf.png should be 40x40, and we'll also need a lambdaconf@2x.png at 80x80, too. LGTM otherwise

**Comment by jdegoes** [comment]
@SethTisue Done!

**Comment by SethTisue** [comment]
heh, I missed this the first time around, but both the filenames and the content should have 2016 not 2015, and you're working off an 11-month old clone of the repo

**Comment by SethTisue** [comment]
I wrote "2015" on a check yesterday :-)

**Comment by jdegoes** [comment]
Arg, those damn year changes! Can't we all just agree to stay in 2015 forever!!!

**Comment by SethTisue** [comment]
thanks!

**Pull request merged**
