### PR TITLE
Add Scala Matsuri 2020

### PR DESCRIPTION
**Pull request by Philippus**

### CODE REVIEW

**Comment by Philippus** [comment]
wow, that was merged faster than the shinkansen.

**Comment by SethTisue** [comment]
post-merge review by @eed3si9n

**Comment by SethTisue** [comment]
this appears to be the beginning of a incipient Scala Ring of Fire, in which fiery red eruptions of functional programming devastate multiple locations around the Pacific Rim:

Screen Shot 2019-11-12 at 11 05 19 PM

**Comment by eed3si9n** [comment]
whoa I didn't realize it was that close together.

**Pull request merged**
