### PR TITLE
mention the new Scala-Spark Gitter rooms

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
fyi @deanwampler

I'm going to go ahead and merge this since the rooms are new and we want them to get off the ground and be successful. But I'll respond promptly to any feedback about wording, etc.

**Comment by SethTisue** [comment]
Markdown fixed in fd6afa7

**Comment by SethTisue** [comment]
perhaps it's improper for me to merge this without leaving time for discussion, so at least me at least justify the addition. certainly we can't list every room for every specific Scala-based technology. but our collective experience on the Scala Gitter and IRC channels is that a significant portion of newcomers to those channels are looking for help with their Spark-based Scala code, and they often aren't getting the help they need, and often their questions require both Scala knowledge and Spark knowledge. the creation of the channels was discussed with the community at https://groups.google.com/d/msg/scala-debate/OVGnIU2SNmc/R4j3hI4cAgAJ and http://apache-spark-developers-list.1001551.n3.nabble.com/Apache-Spark-chat-channel-td19261.html

**Comment by deanwampler** [comment]
​Works for me.

**Comment by deanwampler** [comment]
​Actually, I'm going to delete the "questions" room at the end of the week
(there's a semi-useful discussion there now I don't want to just kill). So,
you can remove that URL from the file. Thanks.

**Comment by SethTisue** [comment]
done in 2f2149645309af20619e70a49d1641e919bec710

**Pull request merged**
