### PR TITLE
Add Functional Scala 2019 conference

### PR DESCRIPTION
**Pull request by kubukoz**

### CODE REVIEW

**Comment by sjrd** [comment]
I'll be clear: I don't like this.

This event was created on purpose at the same time as Scala eXchange, in what I can't help but interpret as retaliation for Skills Matter having uninvited John De Goes. The uninvitation certainly was controversial, but the creation of the other event was not any better. That move has forced too many people to "choose their side", whereas before a large number of people were quite happy to hang out with all interested parties. It was a bad move that I do not approve.

Adding a reference to that competing event on the website would mean some form of endorsement. This is not something I am willing to do.

I won't stand in the way of someone else merging this PR, but I won't be the one clicking the Approve button nor the Merge button.

**Comment by Krever** [comment]
The one thing I demand from `scala` organization is to be apolitical and treat all equally. Typelevel, skillsmater, ZIO or Lightbend can hold their opinions and views but not something as general as `scala`.

**Comment by kubukoz** [comment]
@sjrd i understand. I will get back when I've gathered some thoughts on the situation.

**Comment by SethTisue** [comment]
I agree with Seb.

It's within a conference's rights to decide to uninvite a speaker. It's consistent with live-and-let-live: speak, but not at _our_ conference.

But for one conference organizer to intentionally organize and schedule a competing event to _deliberately sabotage_ someone else's conference is a huge, huge escalation and a kind of open aggression we've never seen before in the Scala community. There is no way this can be construed as live-and-let-live behavior.

I am also very reluctant for scala-lang.org to participate in normalizing this kind of behavior around Scala.

**Comment by kubukoz** [comment]
@sjrd @sethtisue

> This event was created on purpose at the same time as Scala eXchange

Quite likely.

> in what I can't help but interpret as retaliation for Skills Matter having uninvited John De Goes. The uninvitation certainly was controversial, but the creation of the other event was not any better.

I, for one, when informed about John being uninvited from the conference, decided not to come to that conference. Many others did. Having another event for those of us who wouldn't have have gone to eXchange anyway brings no time conflict.

> That move has forced too many people to "choose their side", whereas before a large number of people were quite happy to hang out with all interested parties.

I'm still very happy to hang out with all parties. As well as many people who don't consider John to be a criminal or white supremacist (which would have made a reasonable cause for expelling him from the conference, not controversial like the existing cause).

I certainly hope nobody in their right mind will judge any attendees of either event.

Functional Scala is a free event. One could order tickets to both conferences while paying for one, and attend parts of each.

> Adding a reference to that competing event on the website would mean some form of endorsement. This is not something I am willing to do.

And I was hoping scala-lang.org was a suitable place to find a list of all welcoming conferences related to the Scala language.

People have the right to choose for themselves which conference they want to go to. And I know that many people, given a choice between a general-purpose Scala conference and a functional Scala conference, would choose the latter. If they don't know one is happening, they won't choose it.

> It's within a conference's rights to decide to uninvite a speaker. It's consistent with live-and-let-live: speak, but not at our conference.

Sure. As long as the organizers are willing to accept refund requests for the tickets, which they did (as far as I'm aware).

> But for one conference organizer to intentionally organize and schedule a directly competing event to deliberately sabotage someone else's conference is a huge, huge escalation and a kind of **open aggression** we've never seen before in the Scala community.

Sabotage... aggression... Is anyone being threatened? I'd say this is a stretch.

If anything, this is competition and a means of increasing the variety of choice potential attendees have. They can go to a conference more suited to their needs. That's a good thing.

---

Now, for me, this isn't about retaliation or trying to win over people who were considering to go to the other conference... I just want to see an event I'm speaking at on the official website of the language I love. I'm tired of the drama and just wanted to have the event show up here.

**Comment by jdegoes** [comment]
I of course fully support the right of Skills Matter to disinvite anyone for any reason—even when such decisions may be misinformed, misguided or destructive.

Nonetheless, Skills Matter does not possess an exclusive right to any dates in the calendar year, and event overlaps can and do happen (see: ZIO Hackathon Warsaw, Lambda Ale, and Scala Italy, which all overlapped substantially). This event overlaps because many people were already going to be in town and decided not to attend the Skills Matter event.

It would be unreasonable and highly discriminatory to allow Skills Matter to promote a for-profit event on the Scala language website, and yet deny the same listing to a non-profit event developed by the community and for the community. Especially since this has never been about forcing people to "choose sides" (we all have good friends attending both!), but about providing everyone who planned to travel and would be in London anyway a friendly place to gather and promote the Scala language and community.

Inasmuch as the Scala language website represents the interests of the community, and inasmuch as this website is located on the official Scala organization on Github, it is my strong opinion that this pull request should be merged; and not just this one, but any pull request that adds an event of broad interest to the Scala community (including of course Scala Exchange, which absolutely merits inclusion on the event page).

The listing of Functional Scala is in no way an endorsement of this event, nor the decision to create it; just like the listing of Scala Exchange is in no way an endorsement of that event, nor their decision to disinvite me. Listing these events is an acknowledgment of the fact that both contain content that is tremendously useful for aspiring and practicing Scala developers.

**Comment by nadenf** [comment]
@sjrd  .. I use ZIO, Cats, Play etc all of which work together and come from different entities. 
You only need to choose sides if you _want_ to choose sides.

I really wish people would start thinking of users first and realise that the Scala ecosystem is big enough for everyone to happily coexist.

**Comment by adamgfraser** [comment]
I am strongly supportive of merging this PR and would hope that members of the Scala organization could treat all members of the Scala community with the same respect.

Skills Matter disinvited John from their conference. Whether that was the right thing to do we can all have different opinions about but they were clearly within their rights to do so. John organized a free conference for the Scala community, including many people who hadn't been invited to Skills Matter before. We can have different opinions on that as well but he was also completely within his rights. From the perspective of the Scala organization I would hope that is where the inquiry ends.

It is an event in the Scala community. Put it on the website.  If you have something to say come and give a talk.

**Comment by odersky** [comment]
I don't think scala-lang should get involved in political discussions, which means it should not take sides.

**Comment by fsvehla** [comment]
Thank you, Martin

**Pull request merged**
