### PR TITLE
Replace Google Analytics with self-hosted Plausible

### PR DESCRIPTION
**Pull request by vincenzobaz**
This PR adds replaces Google Analytics with a self hosted Plausible instance.

[Plausible](https://plausible.io/) is open source and privacy-friendly. All the data is stored on the Scala Center' servers.

### CODE REVIEW

**Comment by julienrf** [comment]
I don’t have access to Google Analytics, but is there someone having access to it, and who is opposed to this change?

**Comment by SethTisue** [comment]
@lrytz is something any of us at Lightbend were ever involved with?

**Comment by lrytz** [comment]
I will ask, I believe that the data went into a lightbend-owned account. If desired, could we have access to the data in plausible?

**Comment by julienrf** [comment]
> If desired, could we have access to the data in plausible?

Yes.

**Review by julienrf — APPROVED** [review]

**Comment by julienrf** [comment]
@lrytz Is it OK to merge the PR on lighbend’s side?

**Comment by lrytz** [comment]
I didn't hear back, so yes.

**Comment by lrytz** [comment]
.. my invitation didn't work though, no idea why. I just got to the login page. Can you send it again?

**Pull request merged**
