### PR TITLE
Add 'category' to ScalaCourses training

### PR DESCRIPTION
**Pull request by andy1138**
Hopefully this is makes Mikes training event finally look correct

### CODE REVIEW

**Comment by heathermiller** [comment]
hrm

**Comment by heathermiller** [comment]
🎉 🍻 Thank you Andy!!

**Comment by andy1138** [comment]
Thats a good way to finish the week  😄 

And we should also invite @mslinn to the party 🍺   and hope is training course goes more smoothly than adding it to website 🍹

**Comment by mslinn** [comment]
@andy1138, why thank you for the invitation! I love parties!

Also thank you for taking care of this. So nice to have a working link!

If this course gets enough students we will follow up with our Intermediate Scala course. We'd like to get the word out. [Retweets](https://twitter.com/ScalaCourses/status/781588917363572737) would be much appreciated!

**Pull request merged**
