### PR TITLE
Fix download links on Windows

### LINKED ISSUE #703: Wrong link for window binary download
at https://github.com/scala/scala-lang/blob/e38f2769b2fc7f57854b4d2dfd3742a25ff42ad9/resources/js/functions.js#L270

`os == "Windows"`

where `getOS()` returns `windows`

### PR DESCRIPTION
**Pull request by retronym**
Fixes #703

### CODE REVIEW

**Comment by heathermiller** [comment]
🙊 omg.

**Comment by heathermiller** [comment]
Thank you, @retronym!

**Comment by MasseGuillaume** [comment]
We can ask for https://www.browserstack.com it's free for open source.

**Pull request merged**
